# Local development overrides
logging:
  level:
    root: INFO
    com.nayibit.lifeguide: DEBUG

server:
   port: 8081        # override here if dev needs a different port than the base config

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lifeguide_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

